version: "2"

services:
  nodejs:
    build: ./nodejs
    ports:
      - "8080:8080"
    volumes:
      - ./projects:/usr/src/app
    container_name: webserver

  mongodb:
    image: mongo:latest
    volumes:
       - mongodata:/data/db
    container_name: mongodb
    hostname: mongo
    ports:
      - 27017:27017

volumes:
  mongodata:
    driver: local