version: "2"

services:
  nodejs:
    build: .
    command: nodemon app.js
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    container_name: nodejs